// SPDX-FileCopyrightText: JP Dillingham
// SPDX-FileCopyrightText: 2026 Ahian Fernandez
// SPDX-License-Identifier: GPL-3.0-only

package dev.slsk.internal.messaging.handlers;

/** Events raised while handling server messages. */
public enum ServerMessageEvent {
    DISTRIBUTED_NETWORK_RESET,
    EXCLUDED_SEARCH_PHRASES_RECEIVED,
    GLOBAL_MESSAGE_RECEIVED,
    KICKED_FROM_SERVER,
    PRIVATE_MESSAGE_RECEIVED,
    PRIVATE_ROOM_MEMBERSHIP_ADDED,
    PRIVATE_ROOM_MEMBERSHIP_REMOVED,
    PRIVATE_ROOM_MODERATED_USER_LIST_RECEIVED,
    PRIVATE_ROOM_MODERATION_ADDED,
    PRIVATE_ROOM_MODERATION_REMOVED,
    PRIVATE_ROOM_USER_LIST_RECEIVED,
    PRIVILEGED_USER_LIST_RECEIVED,
    PRIVILEGE_NOTIFICATION_RECEIVED,
    PUBLIC_CHAT_MESSAGE_RECEIVED,
    ROOM_JOINED,
    ROOM_LEFT,
    ROOM_LIST_RECEIVED,
    ROOM_MESSAGE_RECEIVED,
    ROOM_TICKER_ADDED,
    ROOM_TICKER_LIST_RECEIVED,
    ROOM_TICKER_REMOVED,
    SERVER_INFO_RECEIVED,
    USER_CANNOT_CONNECT,
    USER_STATISTICS_CHANGED,
    USER_STATUS_CHANGED
}
